Include STL thread header to fix sleep_for compile error
This fixes the following compile error that occurred on Linux:
    error: ‘sleep_for’ is not a member of ‘std::this_thread’
The sleep_for function is defined in <thread>.