Upgrade to gtest 1.12.1 to fix compile error on Linux
This fixes the following compile error:
    gtest-death-test.cc:1301:24: error: ‘dummy’ may be used uninitialized